rapidsai/ops-bot

- src/config.ts
In hindsight, this should've been set to a default value of `false`. We can potentially set it to `true` in the future if we want it to be an "opt-out" feature.
> Set `external_contributors` to default to `false`

- test/mocks.ts
This PR gives our test mocks names so that they provide more helpful output during test failures.
It also alphabetizes the mocks.
> Provide names for mock functions

- .github/ops-bot.yaml
- README.md
- src/config.ts
- src/index.ts
- src/plugins/CopyPRs/comment.ts
- src/plugins/CopyPRs/index.ts
- src/plugins/CopyPRs/pr.ts
- src/shared.ts
- test/copy_prs.test.ts
- test/fixtures/contexts/issue_comment.ts
- test/fixtures/contexts/pull_request.ts
This PR renames and reworks the `ExternalContributors` plugin to work for _all_ pull requests, instead of just those from external contributors. It's now called `CopyPRs`.
The new behavior works like this:
- Any pull request from an organization member will automatically be copied to the source repository
- Any pull request from a non-organization member will only be copied to the source repository after someone with `write` or `admin` permissions on the repo comments `okay to test` on a PR
- All pull requests that are copied to the source repository will be formatted as `pull-request/<PR_NUM>`
---
Side note, there are a lot of formatting changes in this PR. So at some point, we should implement [prettier](https://prettier.io/) in this repo (with a GH Action Check) so that our code has …
> Rename `ExternalContributors` plugin to `CopyPRs`

- .github/workflows/deploy.yaml
- README.md
- serverless.yaml
- src/config.ts
- src/plugins/RerunTests/index.ts
- src/plugins/RerunTests/rerun_tests.ts
- test/fixtures/contexts/issue_comment.ts
- test/rerun_tests.test.ts
This PR adds a `Rerun Tests` plugin, which listens for comments on a PR and triggers a new CI build if the comment matches a particular regular expression.
> Add `Rerun Tests` plugin

- src/plugins/CopyPRs/pr.ts
- test/copy_prs.test.ts
Since the `ops-bot` is used in other organizations besides `rapidsai`, this PR removes a hardcoded reference to the `RAPIDS` organization and replaces it with a dynamic reference based on the source of the webhook.
> Fix hard-coded org name

- src/plugins/CopyPRs/pr.ts
- test/copy_prs.test.ts
This PR updates the comment for PRs from external contributors to clarify which members can approve the PR for testing.
> Update comment for external contributors

- README.md
- src/plugins/CopyPRs/comment.ts
- src/plugins/CopyPRs/pr.ts
- src/shared.ts
- test/copy_prs.test.ts
This PR adds a new feature to the `CopyPRs` plugin, which allows only a single commit to be tested.
If a PR is commented with `test last commit`, then only the most recent commit will be tested in CI (not subsequent commits, as is the case with `okay to test`).
> Add `test last commit` functionality to `CopyPRs` plugin

- src/plugins/CopyPRs/pr.ts
- test/copy_prs.test.ts
This PR temporarily skips the external contributor comment that gets posted for the `rapidsai` organization. This is to prevent confusion with the existing `Can one of the admins verify this patch?` comment that gets posted as part of our existing CI setup (like [this](https://github.com/rapidsai/cudf/pull/11164#issuecomment-1168999614)).
Once we're fully migrated away from the existing setup, we should revert this PR.
Also worth noting, the `okay to test` comment will still work for this `ops-bot` plugin, we just won't be posting the external contributor comment for any `rapidsai` organization repositories.
> Temporarily remove external contributor comment for `rapidsai` org

- src/plugins/ReleaseDrafter/release_drafter.ts
- test/fixtures/contexts/push.ts
- test/release_drafter.test.ts
This modifies the release drafter plugin to validate branches based on calendar versioning
> Fix Release-Drafter plugin

- src/plugins/AutoMerger/auto_merger.ts
- src/plugins/CopyPRs/comment.ts
- src/plugins/CopyPRs/pr.ts
- src/shared.ts
- test/copy_prs.test.ts
- test/fixtures/responses/list_comments.json
- test/release_drafter.test.ts
- tsconfig.json
The PR adjusts the `Copy PRs` plugin according to the implementation details below:
- current implementation:
- `okay to test` - tests last commit and all subsequent commits
- `test last commit` - tests last commit, but not subsequent commits
- new implementation:
- `/okay to test` - tests last commit, but not subsequent commits
- `okay to test` - this command was removed in favor of `/okay to test`
- `test last commit` - this command was removed
This ensures that all commits must be validated by an organization member with `write` or `admin` permissions before CI will run on any given PR.
I will open a subsequent PR to add an "allow list" of users whose PR commits will automatically be tested under the condition that the commits are signed and verified by GitHub.
> Update `Copy PRs`

- src/plugins/RerunTests/rerun_tests.ts
- src/shared.ts
- test/rerun_tests.test.ts
This PR changes the `rerun tests` command to `/rerun tests`.
Note, that the functionality of this plugin is currently only used by the morpheus organization.
> Change `rerun tests` cmd to `/rerun tests`

- src/plugins/BranchChecker/check_pr.ts
- src/plugins/CopyPRs/pr.ts
- src/plugins/LabelChecker/label_checker.ts
- src/plugins/RecentlyUpdated/check_pr.ts
- src/shared.ts
- test/branch_checker.test.ts
- test/label_checker.test.ts
- test/recently_updated.test.ts
This PR updates some logic to ensure that statuses set on `GPUTester` PRs are always successful.
Additionally, it ensures that any PRs opened by `GPUTester` aren't copied to a `pull-request/*` branch for testing. This has adverse affects for GitHub Actions with the forward-merging PRs.
> Disable `Copy PRs` & Make checks successful for `GPUTester` PRs

- src/plugins/AutoMerger/auto_merger.ts
- src/plugins/AutoMerger/index.ts
- src/plugins/AutoMerger/resolve_prs.ts
- src/shared.ts
- src/types.ts
This PR includes the following changes:
- refactors the `auto_merger` plugin
- adds `check_suite` event support for the `auto_merge`
`check_suite` event support is necessary in order for the `auto_merger` plugin to allow for queuing PRs to be merged with GitHub Actions.
This is because GitHub Actions uses the [Checks API](https://docs.github.com/en/rest/checks) to deliver CI results to commits rather than a conventional commit status.
> Add `check_suite` support for Auto Merger

- README.md
- src/plugins/AutoMerger/resolve_prs.ts
- src/shared.ts
- test/fixtures/responses/list_comments.json
This PR changes the comment required to trigger the auto-merger from `@gpucibot merge` to `/merge`.
It also adds functionality to comment the following message on a PR if someone tries to use `@gpucibot merge`:
```
@<author>, the `@gpucibot merge` command has been replaced with `/merge`.
Please re-comment this PR with `/merge` and use this new command in the future.
```
I'll remove the comment functionality in a few weeks once everyone is accustomed to the change.
> Change merge comment to `/merge`

- src/plugins/CopyPRs/comment.ts
- src/plugins/CopyPRs/pr.ts
- src/shared.ts
- test/copy_prs.test.ts
This PR updates the `CopyPRs` plugin to account for external collaborators.
Before this PR, users that were external collaborators for a particular repository did not have their PRs copied to the source repository for automatic testing even if they had `write` or `admin` permissions on that repository.
This PR fixes that.
Closes #134.
> Update `CopyPRs` plugin to account for trusted external collaborators

- .github/workflows/deploy.yaml
- serverless.yaml
Use OIDC to get AWS credentials in CI. We also need to rename the stack from `gpuci-` to `rapidsai-` as the OIDC credentials policy is using this new prefix
> Use OIDC to get AWS credentials in CI

- src/plugins/AutoMerger/auto_merger.ts
- src/plugins/ReleaseDrafter/draft_template.njk
- src/plugins/ReleaseDrafter/release_drafter.ts
- test/auto_merger.test.ts
- test/release_drafter.test.ts
This PR removes the sanitization functions that removed square brackets (`[]`) and their contents from PR titles for commit messages and release notes.
The tests were also updated.
> Remove PR/commit title sanitization functions

- src/shared.ts
Recently we've been seeing some `422` error codes returned for our HTTP requests to the [_Create a commit status_](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status) endpoint.
The associated error message indicates that we've hit a limit on the statuses for a particular SHA in a given repository.
After analyzing the logs, it doesn't appear that we're _actually_ reaching the limits described by the endpoint.
Therefore we've concluded that it could be an issue on GitHub's end that can be resolved by simply retrying the requests.
This PR adds a retry configuration for our `createCommitStatus` calls.
It will retry 3 times, waiting 10 seconds between each retry.
This retry configuration is described here: …
> Add retries to commit status API requests

- src/plugins/AutoMerger/auto_merger.ts
- test/auto_merger.test.ts
- test/fixtures/responses/list_commits.json
- test/fixtures/responses/list_reviews.json
This PR ensures that `ops-bot` does not crash when attempting to get user information. We have seen a case where Github returned a `400` where there was bad user information.
> Fix bad committer user information

- src/plugins/ForwardMerger/forward_merger.ts
In the case where a forward merger fails, we don't get any clues in the logs as to why. This PR fixes that.
> Log forward-merger error

- .github/workflows/deploy.yaml
- serverless.yaml
- src/index.ts
- src/plugins/ForwardMerger/forward_merger.ts
- test/forward_merger.test.ts
This solves the problem of `rapids-bot`'s failing attempts to merge forward-merger PRs. See https://nvidia.slack.com/archives/CJWBS14NB/p1710956582188569?thread_ts=1710857430.929599&cid=CJWBS14NB for context behind this implementation.
Test: 
PR failing due to checks/pending review: https://github.com/rapidsai/literate-octo-potato/pull/817
PR merged with elevated actor: https://github.com/rapidsai/literate-octo-potato/pull/822
> Use elevated actor to merge forward-mergers

- src/plugins/LabelChecker/label_checker.ts
- src/shared.ts
- test/label_checker.test.ts
PR updates the label checker plugin to correctly skip Forward Merger PRs.
> fix label checker

- .github/workflows/deploy.yaml
The `serverless` framework recently published V4, which includes the licensing changes outlined on the pages below:
- https://www.serverless.com/blog/serverless-framework-v4-a-new-model
- https://www.serverless.com/framework/docs-guides-upgrading-v4
The TL;DR is that V4 of the `serverless` framework is no longer free for organizations with $2M or greater annual revenue.
As a temporary workaround, we can pin to V3. V3 will continue to receive security updates and bug fixes throughout 2024.
We will likely need to make this change in a few different repositories.
> Pin `serverless` framework version

- src/shared.ts
- test/label_checker.test.ts
The actual login name is `rapids-bot[bot]`. PR adjusts the code accordingly.
Example command to verify:
```
curl -L \
-H "Accept: application/vnd.github+json" \
-H "X-GitHub-Api-Version: 2022-11-28" \
https://api.github.com/repos/rapidsai/cugraph/pulls/4433
```
> Fix rapids-bot login name

- src/plugins/AutoMerger/auto_merger.ts
This attempts to solve an issue we saw with pynvjitlink where `/merge` didn't work because the default branch is `main` for that repo. This changes the behavior of the auto-merge to allow merging to `main` if it is the default branch for a repository.
> Allow ops-bot to merge to main if main is the default branch.

- src/plugins/ForwardMerger/forward_merger.ts
- src/shared.ts
The ucx branching convention is currently failing validation. This PR updates the check to pass.
> update versioned_branch check to allow ucxx/py branches

- src/shared.ts
Double quotes causes the strings which should otherwise pass, to fail the regex check
> remove quotes from regex

- src/plugins/ForwardMerger/forward_merger.ts
This fixes a logical bug where we filter the returned branches list with only the RAPIDS versioning compatible regex.
> Fix branches filter to discover ucx versioned branches

- src/plugins/RecentlyUpdated/check_pr.ts
- test/fixtures/responses/list_pulls.json
- test/recently_updated.test.ts
Updates the `recently_updated` plugin to correctly filter out forward merger PRs.
> fix recently updated PR checker
